"""
Shared configuration constants for the SENSD SERS analysis package.
"""

from .model_policies import (
    BATCH_DEVIATION_Z_THRESHOLD,
    GLOBAL_QA_IQR_WHIS,
    GLOBAL_QA_R2_MIN_THRESHOLD,
    GLOBAL_QA_REJECTION_MULTIPLIER,
    PHASE2_INLIER_FEATURE,
    PHASE2_QA_FEATURES,
    PHASE2_RANDOM_STATE,
    PHASE2_RF_N_ESTIMATORS,
    PHASE2_TEST_SIZE,
)
from .spectral_policies import SNAP_SHIFT_DEDUPE_ATOL, SNAP_SHIFT_DEDUPE_RTOL
from .targeted_peaks import (
    TARGETED_PEAK_DEFAULT_ANCHORS_CM1,
    TARGETED_PEAK_DEFAULT_COUNT,
    TARGETED_PEAK_SEARCH_HALF_WIDTH_CM1,
)

__all__ = [
    "BATCH_DEVIATION_Z_THRESHOLD",
    "GLOBAL_QA_IQR_WHIS",
    "GLOBAL_QA_R2_MIN_THRESHOLD",
    "GLOBAL_QA_REJECTION_MULTIPLIER",
    "PHASE2_INLIER_FEATURE",
    "PHASE2_QA_FEATURES",
    "PHASE2_RANDOM_STATE",
    "PHASE2_RF_N_ESTIMATORS",
    "PHASE2_TEST_SIZE",
    "SNAP_SHIFT_DEDUPE_ATOL",
    "SNAP_SHIFT_DEDUPE_RTOL",
    "TARGETED_PEAK_DEFAULT_ANCHORS_CM1",
    "TARGETED_PEAK_DEFAULT_COUNT",
    "TARGETED_PEAK_SEARCH_HALF_WIDTH_CM1",
]
