"""
Shared analysis-policy constants.

These constants preserve the current analytical behavior while centralizing
cross-module policy values that were previously duplicated in multiple files.
"""

GLOBAL_QA_REJECTION_MULTIPLIER = 2.0
GLOBAL_QA_R2_MIN_THRESHOLD = 0.80
GLOBAL_QA_IQR_WHIS = 1.5

BATCH_DEVIATION_Z_THRESHOLD = 2.0

PHASE2_INLIER_FEATURE = "integral_area"
PHASE2_QA_FEATURES = (PHASE2_INLIER_FEATURE,)
PHASE2_TEST_SIZE = 0.2
PHASE2_RANDOM_STATE = 42
PHASE2_RF_N_ESTIMATORS = 100

# Phase 2 hyperparameter search (RandomizedSearchCV on the training split only).
# Skipped when the training set is smaller than PHASE2_TUNING_MIN_TRAIN_SAMPLES or
# when stratified CV is not viable (too few samples per class).
PHASE2_HYPERPARAMETER_TUNING = True
PHASE2_TUNING_MIN_TRAIN_SAMPLES = 30
PHASE2_TUNING_CV_SPLITS = 3
PHASE2_TUNING_RANDOM_SEARCH_ITER = 12
PHASE2_RF_SEARCH_N_ESTIMATORS = (50, 100, 200, 300)
PHASE2_RF_SEARCH_MAX_DEPTH = (None, 8, 16, 24, 32)
PHASE2_RF_SEARCH_MIN_SAMPLES_LEAF = (1, 2, 4)
PHASE2_SVM_SEARCH_C = (0.1, 1.0, 10.0, 50.0, 100.0)
PHASE2_SVM_SEARCH_GAMMA = ("scale", "auto")

__all__ = [
    "BATCH_DEVIATION_Z_THRESHOLD",
    "GLOBAL_QA_IQR_WHIS",
    "GLOBAL_QA_R2_MIN_THRESHOLD",
    "GLOBAL_QA_REJECTION_MULTIPLIER",
    "PHASE2_INLIER_FEATURE",
    "PHASE2_QA_FEATURES",
    "PHASE2_RANDOM_STATE",
    "PHASE2_HYPERPARAMETER_TUNING",
    "PHASE2_RF_N_ESTIMATORS",
    "PHASE2_RF_SEARCH_MAX_DEPTH",
    "PHASE2_RF_SEARCH_MIN_SAMPLES_LEAF",
    "PHASE2_RF_SEARCH_N_ESTIMATORS",
    "PHASE2_SVM_SEARCH_C",
    "PHASE2_SVM_SEARCH_GAMMA",
    "PHASE2_TEST_SIZE",
    "PHASE2_TUNING_CV_SPLITS",
    "PHASE2_TUNING_MIN_TRAIN_SAMPLES",
    "PHASE2_TUNING_RANDOM_SEARCH_ITER",
]
